### ISSUE TITLE
get_weighted_text_embeddings_flux1 yields an error for too many tokens for the model

### ISSUE THREAD

**Issue by jonathanbiard** [xhinker/sd_embed#11]
When I run a test for a very long prompt through `get_weighted_text_embeddings_flux1`, I get the following error:
```
Token indices sequence length is longer than the specified maximum sequence length for this model (198 > 77). Running this sequence through the model will result in indexing errors
```

However, the goal of this implementation is to overcome the 77 token limitation so I'm uncertain why this is happening.

As a side note, I also had to block the printing by redirecting `stdout` to `devnull` since it's outputting the shape every time it executes. It would be nice if this printing was removed or if being verbose would at least be an option. For cloud implementations, unnecessary logging incurs unnecessary additional costs.

**Comment by xhinker** [comment]
The warning is output from the tokenizer_1, the CLIP tokenizer. we can safe to ignore it. For flux, only pool embedding is used, and I avg pool all the tokens, meanwhile, T5 don't have this 77 limitation, I also added weight to it. 

My test shows the result a bit better than the default Diffuser embedding logic. 

>It would be nice if this printing was removed or if being verbose would at least be an option.
Will remove the printing next, thanks

**Comment by jonathanbiard** [comment]
> The warning is output from the tokenizer_1, the CLIP tokenizer. we can safe to ignore it. For flux, only pool embedding is used, and I avg pool all the tokens, meanwhile, T5 don't have this 77 limitation, I also added weight to it.
> 
> My test shows the result a bit better than the default Diffuser embedding logic.
> 
> > It would be nice if this printing was removed or if being verbose would at least be an option.
>
> Will remove the printing next, thanks

Thanks for the clarification!

**Comment by dieptran2500** [comment]
> The warning is output from the tokenizer_1, the CLIP tokenizer. we can safe to ignore it. For flux, only pool embedding is used, and I avg pool all the tokens, meanwhile, T5 don't have this 77 limitation, I also added weight to it.
> 
> My test shows the result a bit better than the default Diffuser embedding logic.
> 
> > It would be nice if this printing was removed or if being verbose would at least be an option.
> > Will remove the printing next, thanks

Hello, thank for you library, but today, i still get them warning "Token indices sequence length is longer than the specified maximum sequence length for this model (xxx > 77). Running this sequence through the model will result in indexing errors
", do if do not use your library, the warning is the same as above, i wonder where is this run correctly

**Comment by xhinker** [comment]
> > The warning is output from the tokenizer_1, the CLIP tokenizer. we can safe to ignore it. For flux, only pool embedding is used, and I avg pool all the tokens, meanwhile, T5 don't have this 77 limitation, I also added weight to it.
> > My test shows the result a bit better than the default Diffuser embedding logic.
> > > It would be nice if this printing was removed or if being verbose would at least be an option.
> > > Will remove the printing next, thanks
> 
> Hello, thank for you library, but today, i still get them warning "Token indices sequence length is longer than the specified maximum sequence length for this model (xxx > 77). Running this sequence through the model will result in indexing errors ", do if do not use your library, the warning is the same as above, i wonder where is this run correctly

You can simply ignore it, it is source from Diffusers tokenizer
