### ISSUE TITLE
get_weighted_text_embeddings_flux1 device selection meta tensor copy

### ISSUE THREAD

**Issue by Teriks** [xhinker/sd_embed#12]
https://github.com/xhinker/sd_embed/blob/dbd4dad6a980f3427223936e222e2fc725a7ab7a/src/sd_embed/embedding_funcs.py#L1419

I believe this line should be `` t5_prompt_embeds    = pipe.text_encoder_2(prompt_tokens_2.to(device))[0].squeeze(0)`` to avoid a possible meta tensor copy error

**Comment by xhinker** [comment]
ah, yes, thank you

**Comment by xhinker** [comment]
fixed
