### ISSUE TITLE
Add Flux Support

### ISSUE THREAD

**Issue by MohamedAliRashad** [xhinker/sd_embed#9]
It would be nice if this library supported Flux.1

**Comment by xhinker** [comment]
working on it

**Comment by xhinker** [comment]
done

**Comment by RedAndr** [comment]
Unfortunately, it generates different images than text prompt.

**Comment by xhinker** [comment]
> Unfortunately, it generates different images than text prompt.

What do you mean by `generates different images`?

**Comment by xhinker** [comment]
Which one is generated by sd_embed ?

**Comment by RedAndr** [comment]
The second one. Frankly, it doesn't look worse, but just different. I'd expect it to be the same.

**Comment by xhinker** [comment]
I tried many, found taht the `sd_embed` generates slight better image than the Diffuser's default prompt embedding, say,  the first cat is actually not `stray cat`. it has cat collar, is not a stray cat. 

In terms of why different images are generated, I am not quite sure, I build the Flux embedding based on my understanding of the model architecture, not copy from the Diffusers logic. there could be some difference in the implementation.

**Comment by RedAndr** [comment]
Ok, thanks for the explanation!
